---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: percona-xtradb
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: percona-xtradb-secret
    creationPolicy: Owner
  data:
    - secretKey: root
      remoteRef:
        key: percona-xtradb
        property: ROOT_PASSWORD
    - secretKey: operator
      remoteRef:
        key: percona-xtradb
        property: OPERATOR_PASSWORD
    - secretKey: monitor
      remoteRef:
        key: percona-xtradb
        property: MONITOR_PASSWORD
    - secretKey: xtrabackup
      remoteRef:
        key: percona-xtradb
        property: XTRABACKUP_PASSWORD
    - secretKey: WORDPRESS_DB_PASSWORD
      remoteRef:
        key: pixyblog
        property: WORDPRESS_DB_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: database-backup
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: database-backup
        property: AWS_SECRET_ACCESS_KEY
