apiVersion: v1
kind: Secret
metadata:
  name: insurgency-sandstorm-adminstxt
  namespace: gaming
stringData:
  Admins.txt: ENC[AES256_GCM,data:aAasFSWFek4eWxl8Mo/VXfWz,iv:L0DMz+ds5Y98W+T99lW12IOi8ViItXB0pwpvHXT5Ci4=,tag:qofqzG7w1nOyamw9PH4E3Q==,type:str]
sops:
  age:
    - recipient: age1x8yqlz3z8ck28vcmyr07tfq85jpr2gc37w0r6y9jj6z69agnvvpsvnw3wz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIekwwa3JLSUR4TGpsaG9V
        ZjQ5SDBBakdaVHI0OE1EZjlEV011RkFOWW1rClB3Wks4M1pvZDE5K1FJSlBJUGJj
        RFhIQ2NNZldWQ0ZJUEs3RitTT2g4L0UKLS0tIEZMcUp0NmdybE4wSmdVRVAySHVw
        amU5KzR0dWlTZmZ2dlEwc251TGlOSFUKQq4ByzjQgmHCosSBCoOFHbi+MeLr0aTk
        wqGJgY6ELKXRyFbBIosUA1GvKGc+jkd2PsqZhzt6QUqkIOjCvvIb1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T04:16:13Z"
  mac: ENC[AES256_GCM,data:hJ2xpbosuNOTC2b3btZ9plWdsuUBW1afpWN24VsQaKY2iKqj9nea6TtQnllng5aLaAD9VFJL9Ujosz1npZqbgT6XxnZLKJKrjeDYq1TTkAQQEkkQT87nzAmWIt/Jo0877w1EIyEYlgfx2aGOMBO3DU1mu9ZzGs5qYaO+FwNzleI=,iv:6rGnGJt/zwP6IaJqnIjCP+5Qub68eoDmjnf7Kze6tx8=,tag:c+TS0aUdRJdMvy9+wpsu9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: insurgency-sandstorm-gameusersettingsini
  namespace: gaming
stringData:
  GameUserSettings.ini: ENC[AES256_GCM,data:dfDFzWeHb3kTRnUzFPg8JkkgmY0M1PYCUOEXBPkgXQ1UxY+nnCshzq6BlimObOziJh3jbhJw8rl53WDjVmFauEheymholmDuK3S5VlPpSLzxVzGQJ6bWDZbNGaVxVS60t4WwFSHsvOGRmYElO3fJkwL4xQNeQxt+fRoDGXQKhuWkpVLidNoYj7dXLqUU8D0KK7itoOlhIVb8bD9aVHgA+m/+BvNSVEAkSwCn57laJasf2Fbm9/xBYCf7mQG7a7ce4gcWKzsGa888cOZXgKaWw6IepqLIDZ2HCvYlwHprdvKsTOosn5Ie2f30ZV8900ll2S/P85/MisUFeC/UF4CtTD1/Ls5JdgNPCG/ugnPOTK0=,iv:GyJbHexCL29n1sfGfX79zZFM9Wu44xlAGOzqyftQvgU=,tag:Q4cF8puvB8kzfFkOtd0Wbg==,type:str]
sops:
  age:
    - recipient: age1x8yqlz3z8ck28vcmyr07tfq85jpr2gc37w0r6y9jj6z69agnvvpsvnw3wz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIekwwa3JLSUR4TGpsaG9V
        ZjQ5SDBBakdaVHI0OE1EZjlEV011RkFOWW1rClB3Wks4M1pvZDE5K1FJSlBJUGJj
        RFhIQ2NNZldWQ0ZJUEs3RitTT2g4L0UKLS0tIEZMcUp0NmdybE4wSmdVRVAySHVw
        amU5KzR0dWlTZmZ2dlEwc251TGlOSFUKQq4ByzjQgmHCosSBCoOFHbi+MeLr0aTk
        wqGJgY6ELKXRyFbBIosUA1GvKGc+jkd2PsqZhzt6QUqkIOjCvvIb1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T04:16:13Z"
  mac: ENC[AES256_GCM,data:hJ2xpbosuNOTC2b3btZ9plWdsuUBW1afpWN24VsQaKY2iKqj9nea6TtQnllng5aLaAD9VFJL9Ujosz1npZqbgT6XxnZLKJKrjeDYq1TTkAQQEkkQT87nzAmWIt/Jo0877w1EIyEYlgfx2aGOMBO3DU1mu9ZzGs5qYaO+FwNzleI=,iv:6rGnGJt/zwP6IaJqnIjCP+5Qub68eoDmjnf7Kze6tx8=,tag:c+TS0aUdRJdMvy9+wpsu9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
