apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-adminstxt
    namespace: gaming
stringData:
    Admins.txt: ENC[AES256_GCM,data:rVEICwOXEegnBG225uOJBsgp,iv:sqTXDIMGK9SvhWsvPr536Mrnp37hginI7HSz+BdWVDs=,tag:I9nBYVTvKkW5YKYaMcJZ5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10xxw4pck9kzfespa7g53ktcj3gettukrd6v45s9lq8fsh5gyv5vq5y8vv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzenoweDFmQVpHYnFEcTJv
            UXgraStwQnBXYmVDQjZFVGhma2JiNTVQVFEwCjRaWmU4MEdaTlBMSW9iSnhaWEV4
            eDdqdTlVbkw0RGlYTTh4VjdjMFRSTmsKLS0tIC94Y0tVQWtCTjFFSWFlaXFMUlNS
            RDNXbkNocjRpODFXWU5XWUgzQ3RGVXcKONs+gKJ4Pf4Xy14Jg6dGEbS13ET4zIyM
            WTaAthEAtaFCEclvqVYXXCYl6gFDr9Y2GKkcdTQSDquZ5p+BDzg/MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T01:32:42Z"
    mac: ENC[AES256_GCM,data:NF2ncCBAJ2Qmm0mVdA96YWBt8T0wm7Nj0KAB67BiaWEyNrugDudGHDi5xaXH6xuhgKZSSUSlgYTp5w5UeuXwf3+ekS+5O7eBMQNDAy0iwyHwW9v9msZwiyORqAeiM2Qoms+nSTUsApBmkJhK6EevGO8h/ys61/7IrGjAUArhlew=,iv:v2X+b6osOWV5yEcLvXKpcgCChcgOI4mglIDfWOkl490=,tag:HcrpQFsiUVZTxxWAH9W89A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-gameusersettingsini
    namespace: gaming
stringData:
    GameUserSettings.ini: ENC[AES256_GCM,data:eUAwIC9EItrIh8RW2OQU+18EKeV93w4NoK/DoLKU9tWgv0K7HRSwxoTLxSADXEeoGxpIMlTsq6a6ePR+sBtKCtcq4DiwoTuBvrY1/s+6cvAJbSQI5gcv3uuz9rm7aGhPwl7XdX287XtVkhGQz+x2sI8grfqano69+fJfM5MYJGKCI0znTNZFuWiT6HcuLe2CHyzIGFKJRf2JPJ/S2WFI9kZBH2mgSiOlI2hYL7EuH6J5v6VGuy3cE4gUUuFP6hSF/7NUsOCFRaMUUgrO7WKj1NRwKyLiEUd9wLlRhvnErDInykdPv7DapY3zteTQvJx2bkLrV9G+j3VVEiR/avQuEilJg15x25V4szZgiZjPZxE=,iv:KJBpNYoEtf8n7DY7PihY35XBKm+HjIUXYso/s0Ag2zA=,tag:Hf0+FI/OJT9lfKV20w9gEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10xxw4pck9kzfespa7g53ktcj3gettukrd6v45s9lq8fsh5gyv5vq5y8vv5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzenoweDFmQVpHYnFEcTJv
            UXgraStwQnBXYmVDQjZFVGhma2JiNTVQVFEwCjRaWmU4MEdaTlBMSW9iSnhaWEV4
            eDdqdTlVbkw0RGlYTTh4VjdjMFRSTmsKLS0tIC94Y0tVQWtCTjFFSWFlaXFMUlNS
            RDNXbkNocjRpODFXWU5XWUgzQ3RGVXcKONs+gKJ4Pf4Xy14Jg6dGEbS13ET4zIyM
            WTaAthEAtaFCEclvqVYXXCYl6gFDr9Y2GKkcdTQSDquZ5p+BDzg/MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T01:32:42Z"
    mac: ENC[AES256_GCM,data:NF2ncCBAJ2Qmm0mVdA96YWBt8T0wm7Nj0KAB67BiaWEyNrugDudGHDi5xaXH6xuhgKZSSUSlgYTp5w5UeuXwf3+ekS+5O7eBMQNDAy0iwyHwW9v9msZwiyORqAeiM2Qoms+nSTUsApBmkJhK6EevGO8h/ys61/7IrGjAUArhlew=,iv:v2X+b6osOWV5yEcLvXKpcgCChcgOI4mglIDfWOkl490=,tag:HcrpQFsiUVZTxxWAH9W89A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
