---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-discord
  labels:
    app.kubernetes.io/name: alertmanager-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-discord
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-discord
    spec:
      containers:
        - name: alertmanager-discord
          image: ghcr.io/masgustavos/alertmanager-discord:v0.4.3
          ports:
            - containerPort: 9094
              name: http
          env:
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: alertmanager-secret
                  key: DISCORD_WEBHOOK_URL
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
  labels:
    app.kubernetes.io/name: alertmanager-discord
spec:
  selector:
    app.kubernetes.io/name: alertmanager-discord
  ports:
    - port: 9094
      targetPort: http
      protocol: TCP
      name: http
