---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./_pvc/ks.yaml
  - ./lidarr/ks.yaml
  - ./nextcloud/ks.yaml
  - ./plex/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./youtubedl/ks.yaml
