---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: percona-xtradb
  namespace: databases
spec:
  path: ./kubernetes/apps/databases/percona-xtradb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: percona-xtradb-cluster
  namespace: databases
spec:
  dependsOn:
    - name: percona-xtradb
    - name: external-secrets-stores
      namespace: kube-system
  path: ./kubernetes/apps/databases/percona-xtradb/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-settings
        kind: ConfigMap
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
