# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:0sMobnmBtsor+BVRyuYyA6HHHEFpo+1XPQSf/YfaL7QLd0f94/IH5g==,iv:naB+2nTNOXI6oudwJ0ewUY+dYmM1XgpepY12IVQgusU=,tag:OtNWbGtMU40fyoM+rPpRQA==,type:str]
sops:
  age:
    - recipient: age1x8yqlz3z8ck28vcmyr07tfq85jpr2gc37w0r6y9jj6z69agnvvpsvnw3wz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaEMzMEh0cmVMR3RIZXpM
        Y1AzNnRMMHZ3NmdHdHhKd1F2ZlRYNUdUcXpnCkYzeVBPQTR1K0NCNUhrZ25QeC9m
        WWFCajlsdTBHeVJ2SFNOQU1qcVZvaFEKLS0tIFMvWmExYUkyM2ZvWlhVSGVISVZF
        Z3NUa1VVNi9QZHowVmZTRTM4ZEVoWW8K8sE0DxkJL4z2wdJzJgBjkZSvSbwMb7D0
        sEto8HoMVPqfK5PMAQouA+MMiJa5ZQv7QOYzdakT5lalbN1YC6a0Pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T20:33:12Z"
  mac: ENC[AES256_GCM,data:Q0RMjBa+SwyJb+/R/moyQKh/lgQJJ+99a7rzd1uJAg+tuojJxGb100UKHsabDg7BJJHyB0H8CBaGnAhO/Rv6qws8BHOJmvEYM5wXH91Zh1nnoBfl+r81NPfh1GIlJ2Nc9pi+QlEuyJSmKxGjFG0RYt8dh+O4ekSRV8K6p4/mG18=,iv:iqLWG+8N6lj3ukts7CQUkq8aIltJGCbOym1O0RrBCPI=,tag:YBIP3rh9hfyGTGUUpCt83w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
