---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oliverblog
  namespace: pixy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: oliverblog-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        WORDPRESS_DB_HOST: percona-xtradb-haproxy.databases.svc.cluster.local
        WORDPRESS_DB_USER: oliverblog
        WORDPRESS_DB_PASSWORD: "{{ .WORDPRESS_DB_PASSWORD }}"
        WORDPRESS_DB_NAME: oliverblog
  data:
    - secretKey: WORDPRESS_DB_PASSWORD
      remoteRef:
        key: oliverblog
        property: WORDPRESS_DB_PASSWORD
