---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cicada
spec:
  hostnames: ["cicada.${SECRET_DOMAIN}"]
  parentRefs:
    - name: internal
      namespace: kube-system
      port: 443
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: cicada-minecraft-cicadadynmap
      namespace: gaming
      port: 8123
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /