---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nut-server
  namespace: kube-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: nut-server
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      nut-server:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          copy-config:
            image:
              repository: busybox
              tag: latest
            command: ["sh", "-c", "cp /tmp/nut-secret/* /etc/nut/local/"]
        containers:
          main:
            image:
              repository: instantlinux/nut-upsd
              tag: 2.8.3-r3@sha256:edadf0d18b7e240fba0e4073dfcc13f19f93839de0656f4b39752c0cad880cd5
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                memory: 128Mi
          exporter:
            image:
              repository: ghcr.io/druggeri/nut_exporter
              tag: 3.2.3@sha256:a9e6c0100ebc0e8ec2c7a46de8af1366df8abd5d794f175b8ee6b2361819ee6e
            env:
              NUT_EXPORTER_SERVER: localhost
              NUT_EXPORTER_SERVERPORT: "3493"
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 64Mi
        pod:
          securityContext:
            fsGroup: 568

    service:
      main:
        controller: nut-server
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${NUT_LB_IP}
        ports:
          nut:
            port: 3493
            protocol: TCP
      metrics:
        controller: nut-server
        ports:
          metrics:
            port: 9199
            protocol: TCP

    serviceMonitor:
      apc-1500:
        serviceName: nut-server-metrics
        endpoints:
          - port: metrics
            interval: 30s
            scrapeTimeout: 10s
            path: /ups_metrics
            params:
              ups: ["apc-1500"]
      apc-3000:
        serviceName: nut-server-metrics
        endpoints:
          - port: metrics
            interval: 30s
            scrapeTimeout: 10s
            path: /ups_metrics
            params:
              ups: ["apc-3000"]

    persistence:
      secret:
        type: secret
        name: nut-server-secret
        advancedMounts:
          nut-server:
            copy-config:
              - path: /tmp/nut-secret
                readOnly: true
      config:
        type: emptyDir
        advancedMounts:
          nut-server:
            copy-config:
              - path: /etc/nut/local
            main:
              - path: /etc/nut/local
