---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-nfs
spec:
  storageClassName: ''
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: ${SECRET_FILESERV_BASE_PATH}/mosquitto
    server: ${SECRET_FILESERV_IP}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
