---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bedrock
  namespace: gaming
spec:
  releaseName: bedrock
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: bedrock
  values:
    replicaCount: 1
    image:
      repository: itzg/minecraft-bedrock-server
      tag: 2025.12.1

    resources:
      requests:
        memory: 8Gi
        cpu: 1500m
      limits:
        memory: 16Gi
        cpu: 5000m

    minecraftServer:
      # This must be overridden, since we can't accept this for the user.
      eula: 'TRUE'
      # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
      version: 1.21.124.2
      # One of: peaceful, easy, normal, and hard
      difficulty: normal
      # A comma-separated list of player names to whitelist.
      whitelistUsers: grounddragoon63,Rgfff1222,2535450030010387,
      # A comma-separated list of player names who should be admins.
      ops: 2535450030010387
      # A comma-seperated list of xuid's for members on server with no
      # whitespaces.
      # ex: ops: "12345678,0987654"
      members:
      # A comma-seperated list of xuid's for visitors on server with no
      # whitespaces.
      # ex: ops: "12345678,0987654"
      visitors:
      # Max connected players.
      maxPlayers: 10
      # The world is ticked this many chunks away from any player.
      tickDistance: 4
      # Max view distance (in chunks).
      viewDistance: 10
      # The "level-name" value is used as the world name and its folder name. The player may also copy their saved game folder here, and change the name to the same as that folder's to load it instead.
      levelName: level
      # Define this if you want a specific map generation seed.
      levelSeed:
      # One of: creative, survival, adventure, spectator
      gameMode: survival
      # Permission level for new players joining for the first time (visitor, member, operator)
      defaultPermission: visitor
      # After a player has idled for this many minutes they get kicked.
      playerIdleTimeout: 120
      # One of: DEFAULT, FLAT, LEGACY
      levelType: DEFAULT
      # Force clients to use texture packs in the current world
      texturepackRequired: false
      # This is the server name shown in the in-game server list.
      serverName: "Minion's Madness"
      # Check accounts against Minecraft account service.
      onlineMode: true
      # Maximum number of threads the server tries to use. If set to 0 or removed then it uses as many as possible.
      maxThreads: 8
      # Cheat like commands can be used.
      cheats: false
      # Enable emit server telemetry.
      emitServerTelemetry: false
      # Enable lan visibility.
      enableLanVisibility: false
      # IPv4 UDP port of server. If using a nodePort, set serverPort and nodePort to the same value (e.g. 30000) so ping time displays.
      serverPort: 19132
      # type of kubernetes service to use
      serviceType: LoadBalancer
      ## Set the port used if the serviceType is NodePort
      # nodePort:
      #loadBalancerIP:
      # loadBalancerSourceRanges: []
      ## Set the externalTrafficPolicy in the Service to either Cluster or Local
      externalTrafficPolicy: Local
      ## Enable SSH for console access (eg. needed for backup containers like https://github.com/Kaiede/Bedrockifier)
      # Please note: if you use this together with serviceType LoadBAlancer, make sure you have at least Kubernetes v1.26
      enableSSH: false
      ## Set the port used for SSH if the serviceType is NodePort
      # nodePortSSH:
      ## Set the port used for SSH by the service (defaults to 2222)
      # exposedPortSSH:
      ## Set password for SSH access (optional, if not set password will be autogenerated)
      # passwordSSH:

    # turn off the minecraft bedrock server and just run sleep in a loop, this way you can get to the server files to restore a server without the server already have loaded
    # them into memory or something
    # kubectl cp -n minecraft survival-server-minecraft-bedrock-b868f4464-nq22m:/data/worlds/. ./
    restoreMode: false

    ## Additional minecraft container environment variables
    ## Values can be either variable values or `valueFrom` yaml
    ##
    extraEnv:
      {}
      # some_variable: some value
      # another_variable:
      #   valueFrom:
      #     fieldRef:
      #       fieldPath: status.hostIP

    ## Additional environment variables to add to the minecraft container from
    ## ConfigMaps and Secrets
    ##
    envFrom: []

    persistence:
      labels: {}
      ## minecraft data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      storageClass: ""
      dataDir:
        # Set this to false if you don't care to persist state between restarts.
        enabled: true
        existingClaim: bedrock-data
        accessModes:
          - ReadWriteOnce
