# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:D4BPudI8cOYx7R990/UGpBJZIsMBALwac99dAJ10qXfwpOkhAyh4kQ==,iv:/Hh3y075/gAG64nEVKxjP/oW452y+mcD6SbSk0oGf5s=,tag:iNJaLo96f1YzDSbVcX/jXQ==,type:str]
sops:
  age:
    - recipient: age1x8yqlz3z8ck28vcmyr07tfq85jpr2gc37w0r6y9jj6z69agnvvpsvnw3wz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4L3N1YXoxd0o0MDRXWjIx
        TWt5S0EyZ3J3RUF0SHpvVjd4UGhqM0dNNTBzClhzNXBkODVpaFFlNHZFQzhTODA4
        aUtXdTRXR0I5Z25TS214cnN3MXFJMGsKLS0tIElCQ0Nsbm5YeWMxZHg1cXhSM1M0
        a3VEaGNieGZRV2xWaXpuTGdUZUlVaHMKwQGkJxVFOu5PWTsZF3r7X9hZ2lFpg3i8
        wV8AvlizrKPGDjWIERsP5HuVobHrDRCEDs8BBEWCllpEHOE6/l/9ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T17:24:12Z"
  mac: ENC[AES256_GCM,data:O8QhwS7aurcN2kriNk+XV4H1EPbaWyQVUnDo13GSH9LLdOwGy7gbJlJrKqY9LCs6ttM7DE860TOw5xad7/Fyjp1Mq+BjHpBo+O484u4fbmA5a2DCu3fEa9xozl7+bFFN3jF7mctQW7xKZG5bbtb/5qCEjGb5stWs3cA4k8AZmmc=,iv:8fgx6k05aocH6gR4gn85ZmAig5OJfBbHLFfgp5U4z74=,tag:zRuATFZGI07AF+LlU0XEzA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
