---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lidarr-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APIKEY: "{{ .LIDARR_API_KEY }}"
  dataFrom:
    - extract:
        key: lidarr
