---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

components:
  - ../../components/alerts
  - ../../components/common

resources:
  - ./exporters/bazarr-exporter/ks.yaml
  - ./exporters/graphite-exporter/ks.yaml
  - ./exporters/lidarr-exporter/ks.yaml
  - ./exporters/minecraft/ks.yaml
  - ./exporters/prowlarr-exporter/ks.yaml
  - ./exporters/radarr-exporter/ks.yaml
  - ./exporters/smartctl-exporter/ks.yaml
  - ./exporters/sonarr-exporter/ks.yaml
  - ./goldilocks/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./unpoller/ks.yaml
