---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pixy
components:
  - ../../components/common
resources:
  - ./fierypyropixy/ks.yaml
  - ./oliverblog/ks.yaml
  - ./pixyblog/ks.yaml
