---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaming
resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: ark-sa-gameusersettings
    namespace: gaming
    files:
      - ./config/GameUserSettings.ini
  - name: ark-sa-gameini
    namespace: gaming
    files:
      - ./config/Game.ini
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: ark-sa
      app.kubernetes.io/instance: ark-sa
