---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gate
components:
  - ../../components/common
patches:
  - target:
      kind: Namespace
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: not-used
        labels:
          goldilocks.fairwinds.com/enabled: "true"
resources:
  - ./_pvc/ks.yaml
  - ./gate/ks.yaml
