---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./certificate.yaml
  - ./certificate-fierypyropixy.yaml
  - ./external.yaml
  - ./internal.yaml
