---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fierypyropixy
  namespace: pixy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: fierypyropixy-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App config
        POSTGRES_HOST: &dbHost postgres-rw.databases.svc.cluster.local
        POSTGRES_DB: fierypyropixy
        POSTGRES_USER: &dbUser "{{ .POSTGRES_USER }}"
        POSTGRES_PASS: &dbPass "{{ .POSTGRES_PASS }}"
        S3_BUCKET: "{{ .S3_BUCKET }}"
        FPP_ADMIN_PASSWORD: "{{ .FPP_ADMIN_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: fierypyropixy
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: fierypyropixy
    - extract:
        key: cloudnative-pg
