---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaming
components:
  - ../../components/common
resources:
  - ./factorio/ks.yaml
  - ./minecraft/ks.yaml
  - ./sandstorm/ks.yaml
  - ./valheim/ks.yaml
